version: '3.9'
services:
  mermaid:
    image: node:18.16.0-alpine3.18
    stdin_open: true
    tty: true
    working_dir: /mermaid
    volumes:
      - ./:/mermaid
      - root_cache:/root/.cache
      - root_local:/root/.local
    ports:
      - 9000:9000
volumes:
  root_cache:
  root_local: