name: Build

on:
  push: {}
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  build-mermaid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        # uses version from "packageManager" field in package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: '.node-version'

      - name: Install Packages
        run: |
          pnpm install --frozen-lockfile
        env:
          CYPRESS_CACHE_FOLDER: .cache/Cypress

      - name: Run Build
        run: pnpm run build

      - name: Upload Mermaid Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermaid
          path: packages/mermaid/dist

      - name: Upload all packages as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermaid-all
          path: |
            packages/**/dist
            !**/node_modules
