name: E2E - Fork

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        containers: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        # uses version from "packageManager" field in package.json

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        id: cypress
        with:
          start: pnpm run dev:coverage
          wait-on: 'http://localhost:9000'
          parallel: true
        env:
          VITEST_COVERAGE: true
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/cypress/lcov.info
          flags: e2e
          name: mermaid-codecov
          fail_ci_if_error: true
          verbose: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          name: error-snapshots
          path: cypress/snapshots/**/__diff_output__/*
