name: Apply triage label to new issue

on: 
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        add-labels: "Status: Triage"
